[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm ci", "npx prisma generate --schema=server/prisma/schema.prisma"]

[start]
cmd = "npx prisma db push --schema=server/prisma/schema.prisma --accept-data-loss && node server/server.js"
